### ISSUE TITLE
haskell-archlinux 1.3 fails to build in 7.10 due to the Applicative-Monad proposal

### ISSUE THREAD

**Issue by dlight** [archhaskell/archlinux#17]
This commit fixes this issue:

https://github.com/archhaskell/archlinux/commit/b42af62c0398350729bfd4ce582f126723b65d27

But the last release (1.3), released in 2011, doesn't include it.

Could you release a new version with this fix and push to Hackage?

Updating the AUR package would be great too (not sure if you're responsible for it)

https://aur.archlinux.org/packages/haskell-archlinux/

**Comment by dlight** [comment]
Actually, even after applying this commit it fails to build, with

```

Distribution/ArchLinux/SrcRepo.hs:50:3: Warning:
    This binding for ‘valid’ shadows the existing binding
      imported from ‘Data.Map’ at Distribution/ArchLinux/SrcRepo.hs:18:1-20
      (and originally defined in ‘containers-0.5.6.2:Data.Map.Base’)

Distribution/ArchLinux/SrcRepo.hs:83:43: Warning:
    Defined but not used: ‘pkg’
[4 of 5] Compiling Distribution.ArchLinux.CabalTranslation ( Distribution/ArchLinux/CabalTranslation.hs, dist/build/Distribution/ArchLinux/CabalTranslation.o )

Distribution/ArchLinux/CabalTranslation.hs:120:25:
    Not in scope: ‘licenseFile’
    Perhaps you meant ‘licenseFiles’ (imported from Distribution.PackageDescription)

Distribution/ArchLinux/CabalTranslation.hs:122:40:
    Not in scope: ‘licenseFile’
    Perhaps you meant ‘licenseFiles’ (imported from Distribution.PackageDescription)
==> ERROR: A failure occurred in build().

```

What I'm actually trying to do is to install [cabal2arch](https://aur.archlinux.org/packages/cabal2arch/), that depends on haskell-archlinux.

**Comment by ony** [comment]
@dlight you may want to look into comments for #16 . I was told that there is more up-to-date projects [ArchHaskell](https://wiki.archlinux.org/index.php/ArchHaskell) and [Haskell ABS](https://github.com/archhaskell/habs/) that utilize [`cblrepo`](https://github.com/magthe/cblrepo)

Yes `licenseFile` were changed to `licenseFiles` in some recent (two years ago) [`Cabal` update](http://hackage.haskell.org/package/Cabal-1.20.0.0).

**Comment by magthe** [comment]
Maybe I should simply remove `archlinux` since it's bitrotted quite a bit by now?

**Comment by dlight** [comment]
You should remove from AUR, yeah

**Comment by magthe** [comment]
It's not possible to remove it, just to make it an orphan. The ArchHaskell group has not been maintaining that AUR package for several years already.
